### ISSUE TITLE
PR policy

### ISSUE THREAD

**Issue by mdlincoln** [NYPL-publicdomain/data-and-utilities#2]
Thanks for posting all these data! :fireworks: :+1: :laughing: :1234: 

So, do you have a pull request policy?

Since the data here are (presumably) generated from your internal collections management system, the usual pull request system may not work, as you would want to effect changes to either the content or presentation of these data in the upstream CMS and/or export scripts. If you want all suggestions to go through the link you provided, you might consider having a heading within your README.md on Pull Requests reiterating that. Similarly, if you _would_ accept PRs for the documentation in the README itself, or to include new script examples, consider saying so explicitly ([see the Carnegie Museum docs](https://github.com/cmoa/collection#pull-requests)).

**Comment by dericed** [comment]
I assembled a collection of resources that may offer clarity on this topic. See http://bfy.tw/3aZm.

**Comment by mdlincoln** [comment]
@dericed I think my question is not about "how pull requests work" _per se_, but about how the NYPL team would handle them for this particular repo. e.g. if I see a data formatting change I'd like done, is it worth me making the changes myself and submitting a PR, or would it be more efficient to submit an issue, assuming NYPL would have to replicate the scripted changes within their own data export workflow?

**Comment by dericed** [comment]
I don't at all speak for the project, but unless there is some documentation within the repo to indicate an exception to the expected use of GitHub, I'd suggest the following defaults:

- a new pull request be initiated by sending a [new pull request](https://github.com/NYPL-publicdomain/data-and-utilities/compare)
- a new issue be initiated by creating a [new issue](https://github.com/NYPL-publicdomain/data-and-utilities/issues/new)

**Comment by saverkamp** [comment]
@mdlincoln Thanks for the feedback! We've updated our documentation to include a pull request policy and to clarify our preferences for data correction suggestions. In short, we would love your pull requests for code examples, but we are not accepting pull requests for our datasets. You can send us metadata corrections through our Digital Collections feedback form or through email to DigitalCollections@nypl.org. If you have other suggestions for improving this repository, this is the place to do it.

Hope this helps,
Shawn

**Comment by mdlincoln** [comment]
Brilliant! :+1:
