### ISSUE TITLE
Update schedule

### ISSUE THREAD

**Issue by mdlincoln** [NYPL-publicdomain/data-and-utilities#3]
Is there a set update schedule for these data? It would be helpful to have some note in the README file as to how often new/revised data will be committed to the repository (monthly? quarterly? "periodically"? etc.) (please for goodness sake, try to have the answer not be "periodically" :stuck_out_tongue_closed_eyes:)

**Comment by saverkamp** [comment]
Thanks for the feedback. We've updated this in our README.
