### ISSUE TITLE
items 4257398 and 4257398 have wrong dateStart in .ndjson files

### ISSUE THREAD

**Issue by LukaszPawlowski-MS** [NYPL-publicdomain/data-and-utilities#4]
I'm playing with the data you shared and found some data entry issues I think. The start date for the items 4257398 and 4257398 show as "4154".

**Comment by saverkamp** [comment]
Thanks for the feedback. If you would like to contribute corrections to our data, please send them through our form at digitalcollections.nypl.org or email to DigitalCollections@nypl.org.
