### ISSUE TITLE
add link to license in readme?

### ISSUE THREAD

**Issue by mgiraldo** [NYPL-publicdomain/data-and-utilities#8]
like so:

```
### License

See [license](/LICENSE).
```

**Comment by hadro** [comment]
This is already in the readme as the following: 
https://github.com/NYPL-publicdomain/data-and-utilities#attribution

Good enough?

**Comment by mgiraldo** [comment]
i guess it is... but maybe to be consistent with the rest of the repos?

**Comment by hadro** [comment]
Done!
